### ISSUE TITLE
When attempting to run 'feddg', the operation failed

### ISSUE THREAD

**Issue by HoTuanLong** [JeremyCJM/CCST#3]
I am attempting to run feddg using the following command:

`python fed_run.py --mode fedavg --dg_method feddg --source art_painting cartoon sketch --target photo --log`

Unfortunately, I have encountered an error which states that there are missing files called `img_{sample_name}.npy`. I was wondering if you could kindly provide me with instructions on how to create the npy file for the data and assist me in resolving this issue.

**Comment by JeremyCJM** [comment]
Could you copy-paste the complete error message?

**Comment by HoTuanLong** [comment]
Of course, this is the output of my issue

`2023-03-24 02:58:12.779633: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-24 02:58:12.921785: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-03-24 02:58:13.543718: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-03-24 02:58:13.543783: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-03-24 02:58:13.543793: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Device: cuda:0
Building server's model...
/home/ubuntu/miniconda3/envs/ccst/lib/python3.10/site-packages/torchvision/models/_utils.py:252: UserWarning: Accessing the model URLs via the internal dictionary of the module is deprecated since 0.13 and may be removed in the future. Please access them via the appropriate Weights Enum instead.
  warnings.warn(
Preparing data...
Loading pacs amp lists...
seen domain freqs:  ['0', '1', '2']
Prepare 0 ...
Prepare 1 ...
Prepare 2 ...
Source domain (for training) is ['0', '1', '2']
Target domain (for testing) is ['3']
2023-03-24 02:58:14.989835: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2023-03-24 02:58:14.989932: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2023-03-24 02:58:14.989985: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2023-03-24 02:58:14.990036: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory
2023-03-24 02:58:14.990068: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-03-24 02:58:14.991007: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Saving to /home/ubuntu/long.ht/CCST/utils/../logs/../checkpoint/pacs/fedavg_no_fusion_feddg_resnet50_locIter1/Target_3_seed_1/iters100_bs32_lr0.002_class7_694
=============Global iter is 0 ===============
Traceback (most recent call last):
  File "/home/ubuntu/long.ht/CCST/federated/fed_run.py", line 703, in <module>
    result = future.result()
  File "/home/ubuntu/miniconda3/envs/ccst/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ubuntu/miniconda3/envs/ccst/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ubuntu/miniconda3/envs/ccst/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/long.ht/CCST/federated/fed_run.py", line 487, in process_client
    train_loss, train_acc = train_meta(models[client_idx], train_loaders[client_idx], optimizers[client_idx], loss_fun, client_num, device_client, args, iter_idx, logger)
  File "/home/ubuntu/long.ht/CCST/federated/fed_run.py", line 100, in train_meta
    for it, data in enumerate(train_loader): 
  File "/home/ubuntu/miniconda3/envs/ccst/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/ubuntu/miniconda3/envs/ccst/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ubuntu/miniconda3/envs/ccst/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/miniconda3/envs/ccst/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/long.ht/CCST/data/ImageLoader.py", line 317, in __getitem__
    tar_freq = self.amp_loader.get_amp()
  File "/home/ubuntu/long.ht/CCST/data/ImageLoader.py", line 238, in get_amp
    tar_freq = np.load(os.path.join(tar_freq_path))
  File "/home/ubuntu/miniconda3/envs/ccst/lib/python3.10/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/long.ht/CCST/datasets/PACS/1/fit/0/pic_006.npy'`

**Comment by JeremyCJM** [comment]
Sorry for getting back late for you. This is the pre-computed FFT amplitude of the images for the FedDG method. You can refer to the [Official FedDG Repo](https://github.com/liuquande/FedDG-ELCFS) to see how to compute the amplitude.

**Comment by HoTuanLong** [comment]
Thank you for your reply.

But maybe the `prepare_dataset.py` in the FedDG repo has not been completed. How do you generate the .npy file? Could you share your source or guide me to compute, please?
